# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: dat@undercurrent.tech
author_name: phamdat
contract_name: algofi_market
deployment_language: python
preset_name: production
project_name: algofi-contracts

